.TH TPSERVER-CPP 1 "2010-04-18" "Lee Begg" "Thousand Parsec Server"
.SH NAME 
tpserver-cpp \- Thousand Parsec Server in C++
.SH SYNOPSIS
.B tpserver-cpp 
[options]
.SH DESCRIPTION
.B tpserver-cpp
is the C++ implementation of the Thousand Parsec Server.  It listens for TP clients on tcp port 6923 (by default),
both IPv4 and IPv6 (if available). If gnutls was configured and the various files provided, a TPS port is opened on tcp
port 6924.
.SH OPTIONS
.IP "\-\-help or \-h"
Prints help then exits.
.IP \-\-version
Prints the version information then exits.
.IP "\-\-configure or \-C"
Sets the configuration file to read.
.IP "\-\-logging or \-l"
Sets how verbose the logging is, from 0 (debug and up) up to 5 (errors only).
.IP "\-\-debug or \-\-verbose or \-v"
Run in verbose/debug mode (does not daemonize).
.IP "\-\-<key> <value>"
Sets the setting <key> to the value <value>.

.SH "CONSOLE COMMANDS"
If configured, an administration client can connect and use various commands. Some key commands are below.
.IP "server-quit"
Tells the server to tidy up and quit the server.
.IP "turn-end"
Start the end of turn sequence.
.IP "turn-time"
Prints the number of seconds to the end of turn.
.IP "network-stop"
Stops the network and closes all connections.
.IP "network-start"
Starts the network and allows connections.
.IP "status"
Print out version numbers and statuses. 
.SH AUTHOR
Lee Begg <lee at thousandparsec dot net>