Document: tpserver-cpp
Title: Debian tpserver-cpp Manual
Author: <insert document author here>
Abstract: This manual describes what tpserver-cpp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tpserver-cpp/tpserver-cpp.sgml.gz

Format: postscript
Files: /usr/share/doc/tpserver-cpp/tpserver-cpp.ps.gz

Format: text
Files: /usr/share/doc/tpserver-cpp/tpserver-cpp.text.gz

Format: HTML
Index: /usr/share/doc/tpserver-cpp/html/index.html
Files: /usr/share/doc/tpserver-cpp/html/*.html

  
