#! /bin/bash

export BASE=tpserver-cpp-win32
export PREFIX=/opt/$BASE/

export PATH=./win32:/opt/crosstool/gcc-3.3.6-/i686-pc-cygwin/bin:$PATH

if [ x$1 = "xconfigure" ]; then
	./autogen.sh

	libgnutls_CFLAGS="-I/opt/crosstool/built/usr/include"                            \
	libgnutls_LDFLAGS="-L/opt/crosstool/built/usr/lib"                               \
	  \
	./configure --prefix=$PREFIX            \
		--host=i686-pc-cygwin                         \
		--build=i686-linux                            \
		--with-boost=/opt/crosstool/built/usr         \
		--with-boost-signals=boost_signals-gcc-mt-s   \
		--without-mysql                               \
		--without-avahi                               \
		--with-ltdl-include=/opt/crosstool/built/usr/include \
		--with-ltdl-lib=/opt/crosstool/built/usr/lib \
		--with-guile=/opt/crosstool/built/usr

fi

make 2>&1

cd tpserver
/bin/bash ../libtool --tag=CXX   --mode=link i686-pc-cygwin-g++ -I/opt/crosstool/built/usr/include  -g -Wall -I/opt/crosstool/built/usr/include/boost-1_33_1 -I/opt/crosstool/built/usr/include/boost-1_33_1 -export-dynamic   -o tpserver-cpp.exe *.o -L/opt/crosstool/built/usr/lib -lboost_signals-gcc-mt-s "-dlopen" self -lpthread -dlopen ../modules/games/minisec/.libs/libminisec.la -dlopen ../modules/games/risk/.libs/librisk.la -dlopen ../modules/tpcl/guile/.libs/libtpguile.la
cd ..

if [ x$1 = "xpackage" ]; then
	sudo mkdir $PREFIX
	sudo chown $USER $PREFIX

	make install

	# Rewrite the cwd to be relative
	sed --inplace -e"s,$PREFIX,../../," $PREFIX/share/tp/tpserver-cpp.xml

	# Copy the DLL's we need
	cp -rvf /opt/crosstool/built/usr/bin/*.dll $PREFIX/bin

	pushd $PREFIX/bin
	rm -f cygguilereadline-v-17-17.dll
	rm -f cygguile-srfi-srfi-*
	rm -f cygboost_*
	popd

	rm -rf $PREFIX/include

	# Copy the scheme files needed
	cp -rvf /opt/crosstool/built/usr/share/guile/1.8/ice-9 $PREFIX/share/tpserver/tpscheme/guile/

	pushd $PREFIX/..
	zip -r ~/$BASE.zip $BASE
	popd
fi

